name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: hrcosmo.azurecr.io
  IMAGE_NAME: hrcosmo-analytics

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ env.REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Analytics Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $REGISTRY/$IMAGE_NAME:latest \
            -f Dockerfile \
            . \
            --push
